### PR TITLE
navigation changes

### LINKED ISSUE #1: Update Navigation
### Description

We need to make the following updates to the navigation bar on our website.

#### Current Navigation Bar:

- Logo: "django girls"
- Links: Community, Workshops, Resources
- Button: Join the community

#### Required Changes:

1. **Logo Update:**
   - Change "django girls" logo to a new design (provide new logo file if available).

2. **Navigation Links Update:**
   - Add a new link labeled "Blog" between "Workshops" and "Resources".
   - Ensure all links are evenly spaced and maintain consistent styling.

3. **Button Update:**
   - button text to read "Join the community" 
   - Ensure button color and style remain consistent with current design.

4. **Styling Adjustments:**
   - Ensure that all elements in the navigation bar are vertically centered.
   - Maintain responsive design for different screen sizes (desktop, tablet, mobile).

### Attachments:

Screenshot 2024-09-18 at 17 39 43

### PR DESCRIPTION
**Pull request by SABRINAmsuya**
I have done changes on the background of the header and responsiveness.

### CODE REVIEW

**Review by lupyana — CHANGES_REQUESTED** [review]
- [ ] add padding to top and bottom of the naviation bar
- [ ] Add padding / margin to the individual nav items
- [ ] Add a container to the nav bar

**Comment by SABRINAmsuya** [comment]
Okay, done.

**Review by lupyana — CHANGES_REQUESTED** [review]
- There is unwanted space between the nav and top of the page, kindly remove it, see screen shot bellow
- Also remove container-fluid and change to container
- lastly refer to the [commit guidelines](https://github.com/pythontanzania/djangogirlstz/blob/main/GIT.MD)

Screenshot 2024-10-15 at 18 24 05

**Comment by SABRINAmsuya** [comment]
I have already removed the unwanted space but when I try to change the
container-fluid to container, the navbar items get misaligned as seen in
the screenshot below. I'm working on it and i will commit all the changes
together when I'm done.

**Pull request closed without merging**
